package edu.uiowa.icts.protogen.springhibernate.velocity;

import static org.hamcrest.Matchers.containsString;
import static org.junit.Assert.*;

import java.text.SimpleDateFormat;
import java.util.Date;

import org.junit.Test;

public class ControllerMvcTestGeneratorTest {

	@Test
	public void shouldGenerateJavaSourceCodeForSpringMVCTestFile() {
		String packageName = "edu.uiowa.icts.ictssysadmin.controller";
		String className = "ClinicalDocument";
		String jspPath = "/ictssysadmin/clinicaldocument";
		ControllerMvcTestGenerator generator = new ControllerMvcTestGenerator(packageName,className,jspPath);
		
		String sourceCode = generator.javaSourceCode();
	//	System.out.println(sourceCode);
		
		assertThat(sourceCode, containsString("package edu.uiowa.icts.ictssysadmin.controller;"));	
		assertThat(sourceCode, containsString("* Generated by Protogen"));
		
		SimpleDateFormat ft = new SimpleDateFormat ("EEE MMM dd");
		assertThat(sourceCode, containsString(ft.format(new Date())));
		// .substring(1).toLowerCase()
		assertThat(sourceCode, containsString("ClinicalDocumentControllerMvcTest extends AbstractControllerMVCTests"));
		assertThat(sourceCode, containsString("public void addShouldDisplayNewClinicalDocumentForm() throws Exception {"));
		assertThat(sourceCode, containsString("mockMvc.perform(get(\"/ictssysadmin/clinicaldocument/add.html\"))"));
		assertThat(sourceCode, containsString(".andExpect(model().attributeExists(\"clinicalDocument\"))"));
		assertThat(sourceCode, containsString(".andExpect(view().name(\"/ictssysadmin/clinicaldocument/edit\"));"));
		
	}

}
