package edu.uiowa.icts.protogen.springhibernate.velocity;

import static org.hamcrest.Matchers.containsString;
import static org.junit.Assert.*;

import java.text.SimpleDateFormat;
import java.util.Date;

import org.junit.Test;

public class ControllerMvcTestGeneratorTest {

	@Test
	public void shouldGenerateJavaSourceCodeForSpringMVCTestFile() {
		String packageName = "edu.uiowa.icts.ictssysadmin.controller";
		String className = "HostController";
		String jspPath = "/ictssysadmin/host";
		ControllerMvcTestGenerator generator = new ControllerMvcTestGenerator(packageName,className,jspPath);
		
		String sourceCode = generator.javaSourceCode();
		//System.out.println(sourceCode);
		
		assertThat(sourceCode, containsString("package edu.uiowa.icts.ictssysadmin.controller;"));	
		assertThat(sourceCode, containsString("* Generated by Protogen"));
		
		SimpleDateFormat ft = new SimpleDateFormat ("EEE MMM dd");
		assertThat(sourceCode, containsString(ft.format(new Date())));
		
		assertThat(sourceCode, containsString("HostControllerMvcTest extends AbstractControllerMVCTests"));
		assertThat(sourceCode, containsString("mockMvc.perform(get(\"/ictssysadmin/host/add.html\"))"));
		assertThat(sourceCode, containsString(".andExpect(view().name(\"/ictssysadmin/host/edit\"));"));
		
	}

}
