/*
 * @author bkusenda
 * 
 * Generates dao files
 * 
 */
package edu.uiowa.icts.protogen.springhibernate;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import edu.uiowa.webapp.Schema;

public class DAOCodeGenerator extends AbstractSpringHibernateCodeGenerator{

	protected static final Log log =LogFactory.getLog(DAOCodeGenerator.class);
	
	private String interfaceSuffix="Service";
	private String impleSuffix="Home";
	public DAOCodeGenerator(SpringHibernateModel model, String pathBase,String packageRoot) {
		super(model, pathBase, packageRoot);
		(new File(packageRootPath)).mkdirs();
	}


	private void generateDao(DomainClass dc) throws IOException {

		String daoPackageName = model.getPackageRoot() +"." + dc.getSchema().getLowerLabel() +".dao";

		String packagePath = pathBase + "/"	+ daoPackageName.replaceAll("\\.", "/") ;
		
		String interfaceName=""+dc.getIdentifier()+interfaceSuffix;
		String implementationName=""+dc.getIdentifier()+impleSuffix;
		
		generateDaoInteface(dc, interfaceName ,daoPackageName, packagePath);
		
		generateDaoImplementation(dc, implementationName, daoPackageName, packagePath, interfaceName);
		

	}


	private void generateDaoInteface(DomainClass dc, String className , String daoPackageName,
			String packagePath) throws IOException {
		List<String> importList = new ArrayList<String>();
		importList.add("import edu.uiowa.icts.spring.*;");
		importList.add("import "+dc.getPackageName()+".*;");
		
		(new File(packagePath)).mkdirs();
		
	
		File file = new File(packagePath, className	+ ".java");
		if(file.exists() && overwrite==false)
		{
			log.debug("File Exists");
			return;
		}
		
		if(file.exists())
			log.debug("Overwriting file....");
			
		FileWriter fstream = new FileWriter(file);
		BufferedWriter out = new BufferedWriter(fstream);
		
		/*
		 * Print Package
		 */
		out.write("package "+ daoPackageName+";\n");
		lines(out, 1);
		
		/*
		 * Print imports
		 */
		for(String importSt: importList)
			out.write(importSt+"\n");
		
		lines(out, 1);
		out.write("/* Generated by Protogen\n");
		out.write(" *\n");
		out.write(" *\n");
		out.write("*/\n");
		
		lines(out, 2);
		/*
		 * Print interface header
		 * 
		 */
		out.write("public interface "+className+" extends GenericDaoInterface<"+dc.getIdentifier()+"> {\n");
		lines(out,2);
		spaces(out, 4);
		
		if(dc.isUsesCompositeKey())
			out.write("public "+dc.getIdentifier()+"  findById("+dc.getIdentifier()+"Id id);\n");
		else
			out.write("public "+dc.getIdentifier()+"  findById(int id);\n");
		
		lines(out,1);
		out.write("}\n");
		out.close();
	}
	
	
	private void generateDaoImplementation(DomainClass dc,String className, String daoPackageName,
			String packagePath,String interfaceName) throws IOException {
		List<String> importList = new ArrayList<String>();
		importList.add("import edu.uiowa.icts.spring.*;");
		importList.add("import "+dc.getPackageName()+".*;");
		importList.add("import org.apache.commons.logging.LogFactory;");
		importList.add("import org.apache.commons.logging.Log;");
		importList.add("import org.springframework.stereotype.Repository;");
		importList.add("import org.springframework.transaction.annotation.Transactional;");
		
		(new File(packagePath)).mkdirs();
		
		/*
		 * If exists, exit
		 * 
		 */
		File file = new File(packagePath, className	+ ".java");
		if(file.exists() && overwrite==false)
		{
			log.debug("File Exists");
			return;
		}
		
		if(file.exists())
			log.debug("Overwriting file....");
			
		
		
		
		FileWriter fstream = new FileWriter(file);
		BufferedWriter out = new BufferedWriter(fstream);
		
		/*
		 * Print Package
		 */
		out.write("package "+ daoPackageName+";\n");
		lines(out, 1);
		
		/*
		 * Print imports
		 */
		for(String importSt: importList)
			out.write(importSt+"\n");
		
		lines(out, 1);
		out.write("/* Generated by Protogen\n");
		out.write(" *\n");
		out.write(" *\n");
		out.write("*/\n");
		
		lines(out, 1);

		/*
		 * Print class header
		 * 
		 */
		out.write("@Repository\n");
		out.write("@Transactional\n");
		out.write("public class "+className+" extends GenericDao<"+dc.getIdentifier()+"> implements "+interfaceName+" {\n");
		lines(out,2);

		spaces(out, 4);
		out.write("private static final Log log =LogFactory.getLog("+className+".class);");
	
		lines(out,2);
		spaces(out, 4);
		out.write("public "+className+"()");
		lines(out,1);
		spaces(out, 4);
		out.write("{");
		spaces(out, 8);
		out.write("setDomainName(\""+dc.getPackageName()+"."+ dc.getIdentifier()+"\");\n");
		lines(out,1);
		spaces(out, 4);
		out.write("}\n");
		
		lines(out,2);
		spaces(out, 4);
		if(dc.isUsesCompositeKey())
			out.write("public "+dc.getIdentifier()+"  findById("+dc.getIdentifier()+"Id id)\n");
		else
			out.write("public "+dc.getIdentifier()+"  findById(int id)\n");
		
		lines(out,1);
		spaces(out, 4);
		out.write("{");
		lines(out,1);
		spaces(out, 8);
		out.write("return ("+dc.getIdentifier()+")this.sessionFactory.getCurrentSession().get(getDomainName(), id);");
		lines(out,2);

		spaces(out, 4);
		out.write("}\n");
		lines(out,4);
		out.write("}\n");
		out.close();
	}
	
	/*
	 * generates all the primary dao inteface class
	 * 
	 * 
	 */
	private void generateDaoMasterServiceFiles() throws IOException
	{
		for(Schema schema :model.getSchemaMap().keySet())
		{
			List<DomainClass> domainClassList = model.getSchemaMap().get(schema);
			if(domainClassList !=null && domainClassList.isEmpty()==false )
			{
				String daoPackageName = model.getPackageRoot() +"." + schema.getLowerLabel() +".dao";

				String packagePath = pathBase + "/"	+ daoPackageName.replaceAll("\\.", "/") ;

				generateDaoMasterService(model.getSchemaMap().get(schema),schema.getUpperLabel()+"DaoService", daoPackageName,packagePath);
			}
			
			
		}
	
	}
	
	
	/*
	 * generates a primary dao inteface class
	 * 
	 * 
	 */
	private void generateDaoMasterService(List<DomainClass> domainClassList, String className, String daoPackageName,
			String packagePath) throws IOException {
		
		List<String> importList = new ArrayList<String>();
		importList.add("import edu.uiowa.icts.spring.*;");
		importList.add("import org.springframework.beans.factory.annotation.Autowired;");
		importList.add("import org.springframework.stereotype.Component;");
		importList.add("import "+daoPackageName+".*;");
		
		(new File(packagePath)).mkdirs();
		
	
		File file = new File(packagePath, className	+ ".java");
		if(file.exists() && overwrite==false)
		{
			log.debug("File Exists");
			return;
		}
		
		if(file.exists())
			log.debug("Overwriting file....");
			
		FileWriter fstream = new FileWriter(file);
		BufferedWriter out = new BufferedWriter(fstream);
		
		/*
		 * Print Package
		 */
		out.write("package "+ daoPackageName+";\n");
		lines(out, 1);
		
		/*
		 * Print imports
		 */
		for(String importSt: importList)
			out.write(importSt+"\n");
		
		lines(out, 1);
		out.write("/* Generated by Protogen\n");
		out.write(" *\n");
		out.write(" *\n");
		out.write(" *\n");
		out.write("*/\n");
		
		lines(out, 1);
		/*
		 * Print interface header
		 * 
		 */
		out.write("@Component\n");
		out.write("public class "+className+" {\n");
		lines(out,2);
		
		
		for(DomainClass dc: domainClassList)
		{
			String type=""+dc.getIdentifier()+interfaceSuffix;
			String variableName = dc.getLowerIdentifier()+interfaceSuffix;
			lines(out, 3);
			spaces(out, 4);
			out.write("/*********** "+variableName+" ****************/\n");
			spaces(out, 4);
			out.write("private "+type+" "+ variableName+"; \n");
			lines(out, 1);
			out.write(createGetter(type, variableName,4));
			lines(out, 1);
			spaces(out, 4);
			out.write("@Autowired \n");
			out.write(createSetter(type, variableName,4));
			lines(out, 1);
		
		}
		
		lines(out,1);
		out.write("}\n");
		out.close();
	}
	

	

	/*
	 * Public Function to generate java domain code
	 * 
	 */
	public void generate() throws IOException 
	{
		
		for(DomainClass dc: model.getDomainClassList())
			generateDao(dc);
	
		generateDaoMasterServiceFiles();

		
	}

}
